### ISSUE TITLE
get_string() tries to cast unicode string to str in Python 2.x

### ISSUE THREAD

**Issue by movermeyer** [chimpler/pyhocon#104]
Given the following configuration file,

```
a = Å
```

the following code fails:

```
from pyhocon import ConfigFactory
conf = ConfigFactory.parse_file("my_conf_file.conf")
conf.get_string('a')
```

with the exception:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    conf = ConfigFactory.parse_file("my_test_conf.conf")
  File "F:\Repos\pyhocon\pyhocon\config_parser.py", line 51, in parse_file
    return ConfigFactory.parse_string(content, os.path.dirname(filename), resolve)
  File "F:\Repos\pyhocon\pyhocon\config_parser.py", line 90, in parse_string
    return ConfigParser().parse(content, basedir, resolve)
  File "F:\Repos\pyhocon\pyhocon\config_parser.py", line 272, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3900, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3829, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3367, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3367, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3900, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3829, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "F:\Repos\pyhocon\env\lib\site-packages\pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "F:\Repos\pyhocon\pyhocon\config_parser.py", line 148, in unescape_string
    return ConfigUnquotedString(norm_string(tokens[0]))
  File "F:\Repos\pyhocon\pyhocon\config_tree.py", line 463, in __new__
    return super(ConfigUnquotedString, cls).__new__(cls, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc5' in position 0: ordinal not in range(128)
```

This is because you cannot coerce this unicode string to ASCII ([which is done here](https://github.com/chimpler/pyhocon/blob/a229e264e09481e8b02d28703a4d8d9570c052f1/pyhocon/config_tree.py#L202)).

I expected this call to get_string to return the unicode string, especially since the [comments at the top of the function](https://github.com/chimpler/pyhocon/blob/a229e264e09481e8b02d28703a4d8d9570c052f1/pyhocon/config_tree.py#L196) state that get_string takes a basestring as input.

**Comment by Daenyth** [comment]
I think this is the same as #114
