### ISSUE TITLE
pyhocon issue in tool

### ISSUE THREAD

**Issue by tojaish** [chimpler/pyhocon#159]
Hi All,

I am new to python and not very savy at it. i come from scala background and i really liked the typesafe-config and hocon format.

Looking to leverage the same in the python projects.

i did follow up the instructions on installation and as soon as i invoke anything involving pyhocon, i get something like below:

(pyhocon-test) test@labs::~/Repos/test$pyhocon --help
Traceback (most recent call last):
  File "/Users/test/.pyenv/versions/pyhocon-test/bin/pyhocon", line 11, in <module>
    load_entry_point('pyhocon==0.3.41', 'console_scripts', 'pyhocon')()
  File "/Users/test/.pyenv/versions/3.6.4/envs/pyhocon-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/test/.pyenv/versions/3.6.4/envs/pyhocon-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/test/.pyenv/versions/3.6.4/envs/pyhocon-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/test/.pyenv/versions/3.6.4/envs/pyhocon-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/test/.pyenv/versions/3.6.4/envs/pyhocon-test/lib/python3.6/site-packages/pyhocon/tool.py", line 4, in <module>
    from converter import HOCONConverter
ModuleNotFoundError: No module named 'converter'

Any help/pointers are greatly Appreciated. Thank you.

**Comment by derkcrezee** [comment]
Same here

**Comment by derkcrezee** [comment]
Created a pull request for this issue (#161 )

**Comment by darthbear** [comment]
Thanks @derkcrezee. Created a new release with the fix. `pyhocon==0.3.42` Thanks!
