### ISSUE TITLE
Issue with environment variables not expanding correctly

### ISSUE THREAD

**Issue by bkuberek** [chimpler/pyhocon#19]
pyhocon==0.3.1

Hi, 

I am having trouble getting environment variables to work properly. I have tried both `${VAR}` and `${?VAR}`. See config below:

```
# defaults.conf
{
  database {
    host = localhost
    port = 5432
    user = people
    name = peopledb
    pass = D3V_0NLY
  }
}


# environment.conf
{
  include file("defaults.conf")
  database {
    host = ${DB_HOST}
    pass = ${?DB_PASS}
  }
}
```

If the environment variable exists then I get this results, which are invalid and fails when parsing:

```
pyhocon -i config/people.conf -f json
{
  "database": {
    "host": [ConfigValues: 192.168.1.10],
    "port": 5432,
    "user": "people",
    "name": "peopledb",
    "pass": [ConfigValues: 12345]
  }
}
```

If the environment variable doesn't exist I get an exception:

```
pyhocon -i config/people.conf -f json
Traceback (most recent call last):
  File "/Users/bkuberek/projects/service/.venv/bin/pyhocon", line 9, in <module>
    load_entry_point('pyhocon==0.3.1', 'console_scripts', 'pyhocon')()
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/tool.py", line 167, in main
    HOCONConverter.convert(args.input, args.output, args.format)
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/tool.py", line 141, in convert
    config = ConfigFactory.parse_file(input_file)
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/__init__.py", line 32, in parse_file
    return ConfigFactory.parse_string(content, os.path.dirname(filename))
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/__init__.py", line 60, in parse_string
    return ConfigParser().parse(content, basedir)
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/__init__.py", line 195, in parse
    ConfigParser._resolve_substitutions(config, substitutions)
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/__init__.py", line 229, in _resolve_substitutions
    resolved_value = ConfigParser._resolve_variable(config, substitution)
  File "/Users/bkuberek/projects/service/.venv/lib/python2.7/site-packages/pyhocon/__init__.py", line 211, in _resolve_variable
    col=col(substitution.loc, substitution.instring)))
pyhocon.exceptions.ConfigSubstitutionException: Cannot resolve variable ${?DB_HOST} (line: 5, col: 12)
```

**Comment by darthbear** [comment]
Thanks for your detailed bug report! I pushed a fix to the optional-substitutions-fix branch. I'll write some more tests tonight and if things are good, I'll merge into master and push a new release to pypi.

**Comment by darthbear** [comment]
It's pushed to pypi: `pyhocon==0.3.2`. Thanks again for reporting this issue!
